#!/bin/bash --login
#
#PBS -l select=1:ncpus=36
#PBS -l place=excl
#PBS -N bench_c
#PBS -A d171-s1898201
#PBS -l walltime=0:5:0



# Switch to current working directory
cd $PBS_O_WORKDIR/

# Run the parallel program
echo 'RAW output'
echo 'CFLAGS= -g -O3'
echo '# Change log
- flag: -O3
- line 77 for use sign
- line 99 merge two for

- line 27 merge two for
- line 38 for moved to head
- line 44 for merged'
./MD
